name: 'Nightly Manager'

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  dev_nightly:
    uses: imperva/dsfkit/.github/workflows/terraform_simple_cli_nightly.yml@dev
    with:
      branch: dev
      workspace: simple_cli_dev_nightly
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  master_nightly:
    uses: imperva/dsfkit/.github/workflows/terraform_simple_cli_nightly.yml@master
    with:
      branch: master
      workspace: simple_cli_master_nightly
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
